containerRegistry:
  url: quay.io/ukhomeofficedigital/
  restApiRepository:
    name: callisto-timecard-restapi
    tag: latest
  databaseRepository:
    name: callisto-timecard-database
    tag: latest

image:
  repository: quay.io/ukhomeofficedigital/callisto-timecard-restapi
  tag: "latest"
kafka:
  identity: test-timecard
  mskSecretKeyRefName: "callisto-dev-msk"
  bootstrapSecretKeyRefName: "callisto-dev-bootstrap"
  defaultTopic: "test-timecard-topic"
db:
  secretKeyRefName: "callistodev-rds"
  schemaName: "timecard"

service:
  containerPort: 9090

ingress:
  host: test-timecard.dev.callisto-notprod.homeoffice.gov.uk
  tls_secret_name: test-timecard-tls
  cors_origin: "https://*.dev.callisto-notprod.homeoffice.gov.uk"
