{{- if .Values.kafka }}
{{- $passwordSecret := ( include "callisto-base-service.keystore-password" . ) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "callisto-base-service.scripts-configmap-name" . }}
  labels:
    {{- include "callisto-base-service.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob "scripts/kafka/**.sh").AsConfig | nindent 2 }}
  {{- if .Values.kafka.createTopics }}
  topics.txt: |-
    {{- .Values.kafka.createTopics.topicNames | nindent 4 }}
  permissions.txt: |-
    {{- .Values.kafka.createTopics.permissions | nindent 4 }}
  {{- end }}
  kafka.properties: |-
    security.protocol=SSL
    ssl.keystore.location=/keystore/keystore.jks
    ssl.keystore.password={{- $passwordSecret }}
    ssl.key.password={{- $passwordSecret }}
{{- end }}
