{{- $databaseSchema := required ".Values.databaseSchema is required." .Values.databaseSchema -}}
{{- $kafkaIdentity := required ".Values.kafka.identity is required." .Values.kafka.identity -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "callisto-restapi.fullname" . }}
  labels:
    {{- include "callisto-restapi.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "callisto-restapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "callisto-restapi.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
{{- if .Values.kafka }}
          volumeMounts:
            - mountPath: /keystore
              name: keystore-volume
{{- end }}
          env: 
            {{- include "callisto-restapi.databaseEnvironmentVariables" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /v3/api-docs
              port: http
          readinessProbe:
            httpGet:
              path: /v3/api-docs
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: database-changesets
          image: "{{ .Values.image.databaseRepository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
            {{- include "callisto-restapi.databaseEnvironmentVariables" . | nindent 12 }}
          args:
            - "--url=jdbc:postgresql://$(DATABASE_ENDPOINT):$(DATABASE_PORT)/$(DATABASE_NAME)"
            - "--username=$(DATABASE_USERNAME)"
            - "--password=$(DATABASE_PASSWORD)"
            - "--changeLogFile=changelog/db.changelog-main.yml"
            - "--liquibaseSchemaName={{ $databaseSchema }}"
            - "update"
{{- if .Values.kafka }}
        - name: create-keystore
          # TODO: swap bak to ECR
          # image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/callisto/awscli-java-openssl:latest
          image: quay.io/ukhomeofficedigital/awscli-java-openssl:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
            {{- include "callisto-restapi.mskEnvironmentVariables" . | nindent 12 }}
            {{- include "callisto-restapi.kafkaEnvironmentVariables" . | nindent 12 }}
          command: [ "/bin/sh" ]
          args: [ "/scripts/create-keystore.sh", "{{ $kafkaIdentity }}", "/keystore" ,"$(AWS_CERTIFICATE_AUTHORITY_ARN)", "$(BOOTSTRAP_SERVER)", "$(KEYSTORE_PASSWORD)", "$(AWS_ACCESS_KEY)", "$(AWS_SECRET_KEY)"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: keystore-volume
              mountPath: /keystore
        - name: create-topic
          # TODO: Change image back
          # image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/callisto/kafka
          image: bitnami/kafka:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
            {{- include "callisto-restapi.mskEnvironmentVariables" . | nindent 12 }}
            {{- include "callisto-restapi.kafkaEnvironmentVariables" . | nindent 12 }}
          command: [ "/bin/bash" ]
          args: [ "/scripts/create-acls.sh", "$(BOOTSTRAP_SERVER)", "$(KEYSTORE_PASSWORD)", "$(KAFKA_TOPIC)"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: keystore-volume
              mountPath: /keystore
      volumes:
      - name: scripts
        configMap:
            name: {{ include "callisto-restapi.scripts-configmap-name" . }}
      - name: keystore-volume
        emptyDir: { }
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
