---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "callisto-restapi.fullname" . }}
  labels:
    {{- include "callisto-restapi.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Egress
    - Ingress
